### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'bert_config.json'

### ISSUE THREAD

**Issue by opokualbert** [ralphbrooks/tensorflow-tutorials#1]
Hello I was able to run the first notebook successfully. model part - model section is throwing an error. Initially I thought it may be because my data may different than yous because I downloaded the text today from yelp. So I decided to use your dataset and still I get the same error.
`ValueError: invalid literal for int() with base 10: 'bert_config.json'`

below is the code that failed:
`model = TFBertForSequenceClassification.from_pretrained('bert-base-cased', config=config)`
Thank you for your time.

**Comment by ralphbrooks** [comment]
I ran the notebook just now on a ml.p2.xlarge (GPU) instance and on a ml.t2.xlarge (CPU) within Amazon SageMaker with the data in data/yelp_info.json on a conda_tensorflow_p36 notebook and I was not able to replicate your error. 

I am running this with Python 3.65, and my guess is that maybe you are using an older version of python in your notebook. 

To help resolve, please do the following:

1)	I have not confirmed that the notebooks work with anything other than Python 3.65. Please confirm that you are using Python 3.65 using the following code :

```
import sys
sys.version_info
```

2)	In the cell right before the code where you are experiencing an issue, confirm that you are using transformers=2.1.1 with the following code:

```
import transformers
transformers.__version__
```

3)	Run %%debug with the code where you are having an issue. Step into that first line of code, and please identify where the error is occurring (what file name and what line of code). If you can provide the full traceback of the error that would be helpful as well. 

The code that you will run will look something like the following: 
```
%%debug
model = TFBertForSequenceClassification.from_pretrained('bert-base-cased', config=config)
```

4)	If none of the above helps, please run `pip freeze`, and post the packages that you are currently using.

**Comment by ralphbrooks** [comment]
Since there was no response, I am assuming that the issue is resolved. Please open a new issue if I can be of assistance.
